### ISSUE TITLE
AttributeError: 'FDC' object has no attribute 'total_column'

### ISSUE THREAD

**Issue by gezahegnsufaa** [spectraphilic/reflexible#39]
I installed reflexible and found the installation was successful except that there were some warnings.
However, when I try to plot the cummulative sensitivity, I ended up with the following issue:

>>> TC = None
>>> for s,k in H.C:
...     data = H.C[(s,k)]
...     TC = rf.plot_totalcolumn(H, data, map_region='Europe', FIGURE=TC)
... 
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/gezahegn/softwares/reflexible-master/reflexible/plotting.py", line 123, in plot_totalcolumn
    figure = plot_sensitivity(H, data.total_column, data_range=data_range,
AttributeError: 'FDC' object has no attribute 'total_column'

The versions installed are:

reflexible version: 0.5.0, NumPy version: 1.15.4, Python version: 3.6.8, GCC 7.3.0, Platform: linux-x86_64, Byte-ordering:  little

Can any one help me in correcting the error please ? I have also attached the screen shot of the terminal.

![screenshot from 2019-02-20 16-32-56](https://user-images.githubusercontent.com/15801165/53240399-a8c26680-36af-11e9-9602-a1389afba67d.png)

**Comment by FrancescAlted** [comment]
Hi.  It would be nice if you can provide an minimal FLEXPART file that can reproduce the error.  Thanks!

**Comment by gezahegnsufaa** [comment]
Thank you Francesc,

I made the run for the test data given in the reflexible example data with path:
reflexible/uio_examples/Bwd1_V9.02/

**Comment by wjjxjd** [comment]
Hello, have you solved this problem?
