### ISSUE TITLE
AttributeError: 'FDC' object has no attribute 'time_integrated'

### ISSUE THREAD

**Issue by wjjxjd** [spectraphilic/reflexible#40]
import reflexible as rf
fprun = rf.Flexpart("/home/wjj/reflexible-master/reflexible/uio_examples/Fwd1_V9.02/pathnames")
H = fprun.Header 
print(dir(H))
T = rf.read_trajectories(H)
TC = None
for s, k in H.C:
     data = H.C[(s, k)]
     TC = rf.plot_totalcolumn(H, data, map_region='Europe', FIGURE=TC)
     TC = rf.plot_trajectory(H, T, k, FIGURE=TC)
     filename = '%s_
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/wjj/reflexible-master/reflexible/plotting.py", line 94, in plot_totalcolumn
    dmax = data.max
  File "/home/wjj/reflexible-master/reflexible/data_structures.py", line 669, in max
    return self.time_integrated.max()
AttributeError: 'FDC' object has no attribute 'time_integrated'

**Comment by wjjxjd** [comment]
import reflexible as rf
fprun = rf.Flexpart("/home/wjj/reflexible-master/reflexible/uio_examples/Fwd1_V9.02/pathnames")
H = fprun.Header
print(dir(H))
T = rf.read_trajectories(H)
TC = None
for s, k in H.C:
     data = H.C[(s, k)]
     TC = rf.plot_totalcolumn(H, data, map_region='Europe', FIGURE=TC)
     TC = rf.plot_trajectory(H, T, k, FIGURE=TC)
     filename = '%s_tc_%s.png' % (data.species, data.timestamp)
     TC.fig.savefig(filename)

Traceback (most recent call last):
File "", line 3, in 
File "/home/wjj/reflexible-master/reflexible/plotting.py", line 94, in plot_totalcolumn
dmax = data.max
File "/home/wjj/reflexible-master/reflexible/data_structures.py", line 669, in max
return self.time_integrated.max()
AttributeError: 'FDC' object has no attribute 'time_integrated'

**Comment by AragamiShirou** [comment]
Hello, have you solved the problem? I also have the same trouble, just using the example data and codes.

**Comment by wjjxjd** [comment]
In fact, I gave up the package, it was really unworkful, I installed version 10.4. Can directly output nc format

**Comment by wjjxjd** [comment]
In fact, I gave up the package, it was really unworkful, I installed version 10.4. Can directly output nc format. 







------------------ 原始邮件 ------------------
发件人: "アラガミ"<notifications@github.com>; 
发送时间: 2019年9月1日(星期天) 下午4:14
收件人: "spectraphilic/reflexible"<reflexible@noreply.github.com>; 
抄送: "王佳佳"<984008820@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [spectraphilic/reflexible] AttributeError: 'FDC' object has noattribute 'time_integrated' (#40)




Hello, have you solved the problem? I also have the same trouble, just using the example data and codes.

**Comment by AragamiShirou** [comment]
Thanks for your reply. In fact, I'm using flexwrf 3.3. But the output in nc
format seems containing no grid information. And some grid_flux files are
generated not in nc format. I guess the post-process in flexpart might be
useful for grid_flux files.

在 2019年9月1日星期日，wjjxjd <notifications@github.com> 写道：
